# Generated by Django 3.1.1 on 2020-09-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200917_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='image_url',
            field=models.CharField(default='https://www.dailynews.com/wp-content/uploads/2018/03/sgt-l-movie-theaters-0223-1-1.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.CharField(default='https://everyfad.com/static/images/movie_poster_placeholder.29ca1c87.svg', max_length=255),
        ),
    ]
