# Generated by Django 3.1.1 on 2020-09-16 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200917_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='showtime',
        ),
        migrations.AlterField(
            model_name='theater',
            name='movies',
            field=models.ManyToManyField(blank=True, to='api.Movie'),
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_times', models.TextField(default='{"times":[]}')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.theater')),
            ],
        ),
    ]
