# Generated by Django 3.1.1 on 2020-09-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200917_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='movies',
        ),
        migrations.AddField(
            model_name='theater',
            name='showtime',
            field=models.ManyToManyField(blank=True, related_name='showtime', to='api.Showtime'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater', to='api.theater'),
        ),
    ]
