# Generated by Django 3.1.1 on 2020-09-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200917_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='showtime',
        ),
        migrations.AddField(
            model_name='theater',
            name='showtime',
            field=models.ManyToManyField(blank=True, null=True, related_name='showtime', to='api.Showtime'),
        ),
    ]
