# Generated by Django 3.1.1 on 2020-09-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200917_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus hendrerit eros nec urna porta, vel maximus felis pharetra. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec mattis pellentesque nibh, ut dignissim nisi maximus in. Sed egestas luctus nisl. Morbi interdum orci tellus, quis varius turpis aliquam vel. In sed neque blandit, commodo sapien nec, tristique enim. Vestibulum finibus facilisis placerat. Mauris placerat scelerisque tristique.', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='start_times',
            field=models.TextField(default='{"times": ["10:00 WIB", "12:00 WIB", "14:00 WIB", "16:00 WIB", "18:00 WIB", "20:00 WIB", "22:00 WIB"]}'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='showtime',
            field=models.ManyToManyField(blank=True, related_name='showtime', to='api.Showtime'),
        ),
    ]
